const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
(async () => {
 const browser = await chromium.launch({headless:true});
 const page = await browser.newPage({viewport:{width:1366,height:768}});
 const errors = [];
 page.on('pageerror', e => errors.push(e.message));
 await page.goto('file://' + path.resolve('ecoarte/index.html'));
 await page.mouse.move(100,100);
 await page.waitForTimeout(50);
 assert(await page.locator('html').evaluate(e=>e.classList.contains('custom-cursor')));
 await page.locator('#demo').hover();
 assert(await page.locator('#cursor').evaluate(e=>e.classList.contains('is-hover')));
 await page.click('#demo');
 await page.evaluate(()=>Ecoarte.showSlide(2));
 await page.waitForTimeout(100);
 const forward = await page.locator('.slide.active').evaluate(e=>({direction:e.dataset.nav,x:new DOMMatrix(getComputedStyle(e).transform).m41}));
 assert.equal(forward.direction,'forward'); assert(forward.x>0);
 await page.evaluate(()=>Ecoarte.showSlide(3));
 await page.evaluate(()=>Ecoarte.previousSlide());
 await page.waitForTimeout(100);
 const backward = await page.locator('.slide.active').evaluate(e=>({direction:e.dataset.nav,x:new DOMMatrix(getComputedStyle(e).transform).m41}));
 assert.equal(backward.direction,'backward'); assert(backward.x<0);
 await page.locator('#stage').focus();await page.keyboard.press('ArrowRight');
 assert.equal(await page.evaluate(()=>Ecoarte.getState().index),3);
 await page.keyboard.press('ArrowLeft');
 assert.equal(await page.evaluate(()=>Ecoarte.getState().index),2);
 await page.click('#restart');await page.waitForTimeout(50);
 assert.equal(await page.locator('.slide.active').count(),1);
 await page.selectOption('#slide-select','12');
 assert.equal(await page.evaluate(()=>Ecoarte.getState().index),12);
 await page.selectOption('#slide-select','4');
 assert.equal(await page.locator('.slide.active').getAttribute('data-nav'),'backward');
 await page.waitForTimeout(50);
 assert.equal(await page.locator('#leaf-wipe').evaluate(e=>getComputedStyle(e).animationName),'leafwipeBack');
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.evaluate(()=>Ecoarte.showSlide(2));
 assert.equal(await page.locator('.slide.active').evaluate(e=>getComputedStyle(e).animationName),'none');
 await page.mouse.move(210,220);await page.waitForTimeout(30);
 assert.equal(await page.locator('#cursor').evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).m41),210);
 await page.screenshot({path:'ecoarte-ui-desktop.png'});
 const mobile = await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
 await mobile.goto('file://'+path.resolve('ecoarte/index.html'));
 assert.equal(await mobile.locator('#cursor').evaluate(e=>getComputedStyle(e).display),'none');
 await mobile.click('#demo');
 await mobile.dispatchEvent('#stage','touchstart',{touches:[{clientX:300,clientY:300}]});
 await mobile.dispatchEvent('#stage','touchend',{changedTouches:[{clientX:70,clientY:300}]});
 assert.equal(await mobile.evaluate(()=>Ecoarte.getState().index),1);
 assert.deepEqual(errors,[]);
 console.log('PASS: cursor, hover, directional transitions, keyboard, restart, selector, reduced motion, mobile and touch. No JavaScript errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
